# This file is a template, and might need editing before it works on your project.
# Official docker image. "https://github.com/ayazzali/convert_audio_message_to_text__bot.git"
image: docker:latest

services:
  - docker:dind

deploy:
  stage: deploy
  script:
    - whoami
    - ls || dir
    - docker ps -a
    - docker build . -t g3
    - docker stop conv && docker rm conv || true || cd
    - docker run  --name conv --restart unless-stopped  -d   -e TKEY=$CI_TELEGRAM_KEY -e YKEY=$CI_YANDEX_SPEECH_KEY -e LKEY=$CI_LOG_BACK_TG_ID  g3
    - docker logs conv
    - sleep 1m || timeout 60
    - docker ps -a
  only:
    - master
	
	
