# This file is a template, and might need editing before it works on your project.
# Official docker image. "https://github.com/ayazzali/convert_audio_message_to_text__bot.git"
image: docker:latest

services:
  - docker:dind

deploy:
  stage: deploy
  before_script:
    - whoami
    - ls || dir
    - docker ps -a
  script:
    - docker stop conv && docker rm conv || true || cd
    - docker build . -t g3
    # -e LKEY=$CI_LOG_BACK_TG_ID is optional
    # -e Test1=$CI_pub_test -e Test2=$CI_prv_test is just for me (test gitlab vars)
    - docker run  --name conv --restart unless-stopped  -d  -e Test1=$CI_pub_test -e Test2=$CI_prv_test  -e TKEY=$CI_TELEGRAM_KEY -e TKEY=$CI_TELEGRAM_KEY -e YKEY=$CI_YANDEX_SPEECH_KEY -e LKEY=$CI_LOG_BACK_TG_ID  g3
    
    - docker logs conv # keys might be
    - sleep 1m || timeout 60
    - docker ps -a
  only:
    - master
